# Generated by Django 4.2.4 on 2025-03-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnName', models.CharField(max_length=200)),
                ('enName', models.CharField(max_length=200)),
                ('img_url', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=200)),
                ('num_comment_quna', models.IntegerField(default=0)),
            ],
        ),
    ]
