# Generated by Django 4.2.4 on 2025-03-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='num_likes',
            field=models.IntegerField(default=0),
        ),
    ]
