# Generated by Django 4.2.4 on 2025-03-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_attractions_num_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='type',
            field=models.CharField(default='景区', max_length=50),
        ),
    ]
