# Generated by Django 4.2.4 on 2025-03-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0003_attractions_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='if_mapped',
            field=models.IntegerField(default=0),
        ),
    ]
