# Generated by Django 5.1.7 on 2025-04-23 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0004_attractions_if_mapped'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attractions',
        ),
    ]
